    # Use an official Node.js runtime as the base image
    FROM node:18-alpine

    # Set the working directory inside the container
    WORKDIR /clickup_test_project

    ARG DATABASE_URL="postgresql://db_user:password@db:5432/web_app_db"

    # Copy package.json and package-lock.json (or yarn.lock) first to leverage Docker caching
    COPY package*.json ./

    # Install dependencies
    RUN npm install

    # Copy the rest of the application files
    COPY . .

    # Compile TypeScript to JavaScript
    RUN npm run build

    # Expose the application's port
    EXPOSE 3000

    # Resolve host domain
    # RUN chmod 777 /
    # RUN chmod +x ./resolve-host.sh
    # RUN . ./resolve-host.sh
    # RUN chown -R web_app:/web_app/ 

    # Command to start the application
    CMD ["npm", "start"]
