    # Dockerfile Python
    FROM python:3.12.0

    WORKDIR /

    COPY requirements.txt .
    
    RUN pip install --no-cache-dir --use-deprecated=legacy-resolver -r requirements.txt

    COPY . .

    CMD ["locust", "--headless", "-u", "20", "--run-time", "10", "-f", "locust_service/tests/locust_test.py", "--spawn-rate", "20", "--processes", "8"]
    