name: Locust performance test

on:
  push:
    paths:
      - 'web_app/**'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: sh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: make script executable
        run: chmod +x ./run-test.sh
      - name: Run performance tests
        run: ./run-test.sh
