name: Jest unit test

on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: sh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: make script executable
        run: chmod +x ./run-unit.sh
      - name: Run Unit tests
        run: ./run-unit.sh
